import { api } from './client';
export const workspaceApi = {
    list: () => api.get('/workspaces'),
    get: (id) => api.get(`/workspaces/${id}`),
    create: (input) => api.post('/workspaces', input),
    update: (id, input) => api.patch(`/workspaces/${id}`, input),
    remove: (id) => api.delete(`/workspaces/${id}`),
    listMembers: (workspaceId) => api.get(`/workspaces/${workspaceId}/members`),
    addMember: (workspaceId, input) => api.post(`/workspaces/${workspaceId}/members`, input),
    changeMemberRole: (workspaceId, userId, role) => api.patch(`/workspaces/${workspaceId}/members/${userId}`, { role }),
    removeMember: (workspaceId, userId) => api.delete(`/workspaces/${workspaceId}/members/${userId}`),
    listFolders: (workspaceId) => api.get(`/workspaces/${workspaceId}/folders`),
    createFolder: (workspaceId, input) => api.post(`/workspaces/${workspaceId}/folders`, input),
    renameFolder: (folderId, name) => api.patch(`/folders/${folderId}`, { name }),
    moveFolder: (folderId, parentFolderId) => api.patch(`/folders/${folderId}`, { parentFolderId }),
    deleteFolder: (folderId) => api.delete(`/folders/${folderId}`),
    listTeams: (workspaceId) => api.get(`/workspaces/${workspaceId}/teams`),
    createTeam: (workspaceId, name) => api.post(`/workspaces/${workspaceId}/teams`, { name }),
    addTeamMember: (workspaceId, teamId, userId) => api.post(`/workspaces/${workspaceId}/teams/${teamId}/members`, { userId }),
    removeTeamMember: (workspaceId, teamId, userId) => api.delete(`/workspaces/${workspaceId}/teams/${teamId}/members/${userId}`),
    deleteTeam: (workspaceId, teamId) => api.delete(`/workspaces/${workspaceId}/teams/${teamId}`),
    getSharing: (workspaceId) => api.get(`/workspaces/${workspaceId}/sharing`),
    updateSharing: (workspaceId, visibility) => api.patch(`/workspaces/${workspaceId}/sharing`, { visibility }),
    rotateShareLink: (workspaceId) => api.post(`/workspaces/${workspaceId}/sharing/rotate`),
};
